### ISSUE TITLE
Suggesting some renaming and refactoring

### ISSUE THREAD

**Issue by akb89** [akb89/yacab#2]
Guys,

After giving it some thought, I'd like to suggest the following project structure:
```
.
|-- config
|   |-- config.yml
|-- data
|-- yacab
|   |-- authentication
|   |   |-- authenticators
|   |   |    facebook_authenticator.py
|   |   |    google_authenticator.py
|   |   |    twitter_authenticator.py
|   |   authenticator.py
|   |-- exceptions
|   |-- formatting
|   |   |-- formatters
|   |   |    facebook_formatter.py
|   |   |    google_formatter.py
|   |   |    twitter_formatter.py
|   |   formatter.py
|   |-- posting
|   |   |-- posters
|   |   |    facebook_poster.py
|   |   |    google_poster.py
|   |   |    twitter_poster.py
|   |   poster.py
|   |-- getting
|   |   |-- getters
|   |   |    facebook_getter.py
|   |   |    google_getter.py
|   |   |    twitter_getter.py
|   |   getter.py
|   |-- validation
|   main.py
|-- tests
```
The rational behind this is the following:
- We may want to keep the `get` | `post` HTTP semantics as this is what we will send to the different apis in the end. `fetching` breaks the semantics. 
- We may want to remove the `survey` prefix in names as, actually, we're not necessarily handling surveys: we may want to format something else for each api, and the typical example is `survey-posting` where we may post either a survey object or a url. I'm up for a more 'generic' naming standard therefore. 
- We may actually want to handle different kinds of `get` | `post` requests within a single api. We'd like to have apis (twitter/facebook_google) communication factorized, but all 'communication protocols' within a single file for each api. Hence the facebook-***.py/google-***.py/twitter-***.py separation. 

What do you guys think?

**Comment by coetaur0** [comment]
I agree with your points. Your proposition seems to make more sense and is a bit cleaner than what we currently have.

**Comment by akb89** [comment]
Ok, if everyone agrees I'll let you guys handle the refactoring and I'll close the issue when it's committed.

**Comment by coetaur0** [comment]
Ok, I'll take care of it.

**Comment by akb89** [comment]
Some quick remarks:
- the config/ folder should be outside the yacab module (under the project root, beside setup.py and tests/)
- make sure that your docstrings are sphinx-compliant (see [this issue](https://github.com/akb89/nima/issues/21))
- don't put coders' names under each script. A full list of contributers will be added to the README directly

**Comment by coetaur0** [comment]
Ok, I'll make the changes in my next commit. Concerning the sphinx-compliant docstrings, I read in the doc that Sphinx is compatible with Google-style docstings (which is what we have used so far), so should we change it or keep it that way?

**Comment by akb89** [comment]
Ok so I checked and you are right: Google-style docstrings seem to be supported by Sphinx. They are indeed clearer than raw reST so let's go for it.

**Comment by eoptam** [comment]
Hey Alex, you can check the ./documentation/ folder for a flow of yacab, can you give me your comments on it? I did not draw the getters in it yet...

**Comment by akb89** [comment]
Overall, LGTM, but I would add the intermediate input/output of each pipeline module, as it is implemented in the code. For ex:
- config validator output can be a True/False boolean
- Authenticator input will be authentication config parameters 
- Authenticators output can be 400 HTTP response codes
- survey formatters input/output can be json surveys 
- etc. 

Also, you may want to actually rename your module authenticators/formatters/posters by the process names: authentication/formatting/posting. You may also want to consider authentication (checking) as a submodule of the validation pipeline.
